version: '3.3'

services:
  # Mariadb
  mysql:
    image: mariadb:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MyDBRoot123
      MYSQL_DATABASE: cloud_computing
      MYSQL_USER: php
      MYSQL_PASSWORD: php
    networks:
      - mynet
    
 # PHP-FPM 
  myphp:
    build: 
      context: ./src/php
      dockerfile: dockerfile.dockerfile
    ports:
      - "9000"
    depends_on:
      - mysql
    container_name: myphp
    volumes:
      - ./src:/var/www/html
    networks:
      - mynet

  # phpMyAdmin
  phpMyAdmin:
    depends_on:
      - mysql
    image: phpmyadmin:latest
    container_name: phpMyAdmin
    environment: 
        MYSQL_ROOT_PASSWORD: MyDBRoot123 
        PMA_HOST: mysql
        PMA_USER: php
        PMA_PASSWORD: php
    restart: always
    ports:
      - "8082:80"
    networks:
      - mynet

  # nginx
  nginx:
    depends_on:
      - myphp
    image: nginx:latest
    container_name: mynginx
    volumes:
      - ./src/nginx.ini:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    ports:
      - "8080:80"
    networks:
      - mynet

# networks
networks:
  mynet:
    driver: bridge

